import localFont from "next/font/local";
import "./globals.css";
import Nav from "./Nav";
import Header from "./Header";
import { AuthProvider } from "@/app//lib/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-mono`}
      >
      <AuthProvider>
      <header className="bg-gray-800 text-white ">
            <Header />
          </header>
        <div className="flex flex-col h-screen">
        
          <div className="flex flex-1">
            <aside className="w-46 bg-base-300 bg-black  menu-mobile-style" >
              <Nav />
            </aside>

            <main className="p-4 bg-base-200 w-full relative main-container">
            {children}
  
            
            
            </main>
          </div>

          
        </div>
        </AuthProvider>
      </body>
    </html>
  );
}
